version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend/.env:/app/.env  # Mount .env from the root directory to /app/.env in the container
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/.env:/app/.env  # Mount .env from the root directory to /app/.env in the container
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
